name: ML CI Pipeline

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [main, develop]

jobs:
  quality-check:
    name: Code Quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          pip install flake8 black isort
      
      - name: Run flake8
        run: |
          flake8 src/ tests/ --max-line-length=100 --exclude=__init__.py
      
      - name: Check black formatting
        run: |
          black --check src/ tests/
      
      - name: Check import sorting
        run: |
          isort --check-only src/ tests/

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: quality-check
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      
      - name: Run unit tests
        run: |
          pytest tests/test_data.py tests/test_model.py -v
      
      - name: Check test coverage
        run: |
          pytest tests/ --cov=src --cov-report=term --cov-report=xml
          coverage report --fail-under=80

  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: unit-tests
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      
      - name: Run integration tests
        run: |
          pytest tests/test_integration.py -v

  model-validation:
    name: Model Performance
    runs-on: ubuntu-latest
    needs: integration-tests
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      
      - name: Run model performance tests
        run: |
          pytest tests/test_model_performance.py -v